{
  "The harder you work, the luckier you get.":[
    {
        "name": "2022 - 2023",
        "venue": "Social Work Award of PKU (北京大学社会工作奖)"
      },
      {
        "name": "2021 - 2022",
        "venue": "Outstanding Research Award of PKU （北京大学优秀科研奖）"
      },
      {
        "name": "2021 - 2022",
        "venue": "Leo KoGuan Scholarship of PKU（北京大学廖凯原奖学金）"
      },
    {
      "name": "2020 - 2021",
      "venue": "Merit Student of PKU （北京大学三好学生）"
    },
    {
      "name": "2018 - 2019",
      "venue": "National Scholarship （研究生国家奖学金）" 
    },
    {
      "name": "2017 - 2018",
      "venue": "Merit Student of PKU （北京大学三好学生）" 
    },
    {
      "name": "2017 - 2020",
      "venue": "Outstanding Graduate of PKU （北京大学优秀毕业生）"
    },
    {
      "name": "2017 - 2020",
      "venue": "Outstanding Graduate of Beijing （北京市优秀毕业生）"
    },
    {
      "name": "2015 - 2016",
      "venue": "National Scholarship （本科生国家奖学金）"
    },
    {
      "name": "2015 - 2016",
      "venue": "Outstanding Student of Shandong （山东省优秀学生）" 
    },
    {
      "name": "2015 - 2016",
      "venue": "Top Ten Undergraduate （十佳本科生）" 
    },
    {
      "name": "2014 - 2015",
      "venue": "China Telecom Scholarship （中国电信奖学金）"
    },
    {
      "name": "2013 - 2016",
      "venue": "Outstanding Student Cadre （优秀学生干部）" 
    },
    {
      "name": "2013 - 2017",
      "venue": "Outstanding Graduate of Shandong （山东省优秀毕业生）" 
    }
  ]
}
  

